// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InfluencersColumns holds the columns for the "influencers" table.
	InfluencersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString},
		{Name: "account_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// InfluencersTable holds the schema information for the "influencers" table.
	InfluencersTable = &schema.Table{
		Name:       "influencers",
		Columns:    InfluencersColumns,
		PrimaryKey: []*schema.Column{InfluencersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "influencer_platform_account_id",
				Unique:  true,
				Columns: []*schema.Column{InfluencersColumns[2], InfluencersColumns[3]},
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "scheduled_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "scheduled"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "influencer_id", Type: field.TypeString},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_influencers_posts",
				Columns:    []*schema.Column{PostsColumns[6]},
				RefColumns: []*schema.Column{InfluencersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "post_influencer_id_scheduled_time",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[6], PostsColumns[2]},
			},
			{
				Name:    "post_status",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InfluencersTable,
		PostsTable,
	}
)

func init() {
	PostsTable.ForeignKeys[0].RefTable = InfluencersTable
}
