// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/WuPinYi/SocialForge/internal/ent/influencer"
	"github.com/WuPinYi/SocialForge/internal/ent/post"
	"github.com/WuPinYi/SocialForge/internal/ent/predicate"
	"github.com/WuPinYi/SocialForge/internal/ent/user"
)

// InfluencerQuery is the builder for querying Influencer entities.
type InfluencerQuery struct {
	config
	ctx        *QueryContext
	order      []influencer.OrderOption
	inters     []Interceptor
	predicates []predicate.Influencer
	withOwner  *UserQuery
	withPosts  *PostQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InfluencerQuery builder.
func (iq *InfluencerQuery) Where(ps ...predicate.Influencer) *InfluencerQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *InfluencerQuery) Limit(limit int) *InfluencerQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *InfluencerQuery) Offset(offset int) *InfluencerQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InfluencerQuery) Unique(unique bool) *InfluencerQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *InfluencerQuery) Order(o ...influencer.OrderOption) *InfluencerQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryOwner chains the current query on the "owner" edge.
func (iq *InfluencerQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(influencer.Table, influencer.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, influencer.OwnerTable, influencer.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPosts chains the current query on the "posts" edge.
func (iq *InfluencerQuery) QueryPosts() *PostQuery {
	query := (&PostClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(influencer.Table, influencer.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, influencer.PostsTable, influencer.PostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Influencer entity from the query.
// Returns a *NotFoundError when no Influencer was found.
func (iq *InfluencerQuery) First(ctx context.Context) (*Influencer, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{influencer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InfluencerQuery) FirstX(ctx context.Context) *Influencer {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Influencer ID from the query.
// Returns a *NotFoundError when no Influencer ID was found.
func (iq *InfluencerQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{influencer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InfluencerQuery) FirstIDX(ctx context.Context) string {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Influencer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Influencer entity is found.
// Returns a *NotFoundError when no Influencer entities are found.
func (iq *InfluencerQuery) Only(ctx context.Context) (*Influencer, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{influencer.Label}
	default:
		return nil, &NotSingularError{influencer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InfluencerQuery) OnlyX(ctx context.Context) *Influencer {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Influencer ID in the query.
// Returns a *NotSingularError when more than one Influencer ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InfluencerQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{influencer.Label}
	default:
		err = &NotSingularError{influencer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InfluencerQuery) OnlyIDX(ctx context.Context) string {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Influencers.
func (iq *InfluencerQuery) All(ctx context.Context) ([]*Influencer, error) {
	ctx = setContextOp(ctx, iq.ctx, ent.OpQueryAll)
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Influencer, *InfluencerQuery]()
	return withInterceptors[[]*Influencer](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *InfluencerQuery) AllX(ctx context.Context) []*Influencer {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Influencer IDs.
func (iq *InfluencerQuery) IDs(ctx context.Context) (ids []string, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, ent.OpQueryIDs)
	if err = iq.Select(influencer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InfluencerQuery) IDsX(ctx context.Context) []string {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InfluencerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, ent.OpQueryCount)
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*InfluencerQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InfluencerQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InfluencerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, ent.OpQueryExist)
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InfluencerQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InfluencerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InfluencerQuery) Clone() *InfluencerQuery {
	if iq == nil {
		return nil
	}
	return &InfluencerQuery{
		config:     iq.config,
		ctx:        iq.ctx.Clone(),
		order:      append([]influencer.OrderOption{}, iq.order...),
		inters:     append([]Interceptor{}, iq.inters...),
		predicates: append([]predicate.Influencer{}, iq.predicates...),
		withOwner:  iq.withOwner.Clone(),
		withPosts:  iq.withPosts.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InfluencerQuery) WithOwner(opts ...func(*UserQuery)) *InfluencerQuery {
	query := (&UserClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withOwner = query
	return iq
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InfluencerQuery) WithPosts(opts ...func(*PostQuery)) *InfluencerQuery {
	query := (&PostClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withPosts = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Influencer.Query().
//		GroupBy(influencer.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InfluencerQuery) GroupBy(field string, fields ...string) *InfluencerGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InfluencerGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = influencer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Influencer.Query().
//		Select(influencer.FieldName).
//		Scan(ctx, &v)
func (iq *InfluencerQuery) Select(fields ...string) *InfluencerSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &InfluencerSelect{InfluencerQuery: iq}
	sbuild.label = influencer.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InfluencerSelect configured with the given aggregations.
func (iq *InfluencerQuery) Aggregate(fns ...AggregateFunc) *InfluencerSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InfluencerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !influencer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InfluencerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Influencer, error) {
	var (
		nodes       = []*Influencer{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [2]bool{
			iq.withOwner != nil,
			iq.withPosts != nil,
		}
	)
	if iq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, influencer.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Influencer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Influencer{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withOwner; query != nil {
		if err := iq.loadOwner(ctx, query, nodes, nil,
			func(n *Influencer, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := iq.withPosts; query != nil {
		if err := iq.loadPosts(ctx, query, nodes,
			func(n *Influencer) { n.Edges.Posts = []*Post{} },
			func(n *Influencer, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InfluencerQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Influencer, init func(*Influencer), assign func(*Influencer, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Influencer)
	for i := range nodes {
		if nodes[i].user_influencers == nil {
			continue
		}
		fk := *nodes[i].user_influencers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_influencers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (iq *InfluencerQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*Influencer, init func(*Influencer), assign func(*Influencer, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Influencer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(post.FieldInfluencerID)
	}
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(influencer.PostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.InfluencerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "influencer_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *InfluencerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InfluencerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(influencer.Table, influencer.Columns, sqlgraph.NewFieldSpec(influencer.FieldID, field.TypeString))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, influencer.FieldID)
		for i := range fields {
			if fields[i] != influencer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InfluencerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(influencer.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = influencer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InfluencerGroupBy is the group-by builder for Influencer entities.
type InfluencerGroupBy struct {
	selector
	build *InfluencerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InfluencerGroupBy) Aggregate(fns ...AggregateFunc) *InfluencerGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *InfluencerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, ent.OpQueryGroupBy)
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InfluencerQuery, *InfluencerGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *InfluencerGroupBy) sqlScan(ctx context.Context, root *InfluencerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InfluencerSelect is the builder for selecting fields of Influencer entities.
type InfluencerSelect struct {
	*InfluencerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InfluencerSelect) Aggregate(fns ...AggregateFunc) *InfluencerSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InfluencerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, ent.OpQuerySelect)
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InfluencerQuery, *InfluencerSelect](ctx, is.InfluencerQuery, is, is.inters, v)
}

func (is *InfluencerSelect) sqlScan(ctx context.Context, root *InfluencerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
