// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/WuPinYi/SocialForge/internal/ent/influencer"
	"github.com/WuPinYi/SocialForge/internal/ent/post"
)

// InfluencerCreate is the builder for creating a Influencer entity.
type InfluencerCreate struct {
	config
	mutation *InfluencerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ic *InfluencerCreate) SetName(s string) *InfluencerCreate {
	ic.mutation.SetName(s)
	return ic
}

// SetPlatform sets the "platform" field.
func (ic *InfluencerCreate) SetPlatform(s string) *InfluencerCreate {
	ic.mutation.SetPlatform(s)
	return ic
}

// SetAccountID sets the "account_id" field.
func (ic *InfluencerCreate) SetAccountID(s string) *InfluencerCreate {
	ic.mutation.SetAccountID(s)
	return ic
}

// SetStatus sets the "status" field.
func (ic *InfluencerCreate) SetStatus(s string) *InfluencerCreate {
	ic.mutation.SetStatus(s)
	return ic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ic *InfluencerCreate) SetNillableStatus(s *string) *InfluencerCreate {
	if s != nil {
		ic.SetStatus(*s)
	}
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *InfluencerCreate) SetCreatedAt(t time.Time) *InfluencerCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InfluencerCreate) SetNillableCreatedAt(t *time.Time) *InfluencerCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *InfluencerCreate) SetUpdatedAt(t time.Time) *InfluencerCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *InfluencerCreate) SetNillableUpdatedAt(t *time.Time) *InfluencerCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *InfluencerCreate) SetID(s string) *InfluencerCreate {
	ic.mutation.SetID(s)
	return ic
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (ic *InfluencerCreate) AddPostIDs(ids ...string) *InfluencerCreate {
	ic.mutation.AddPostIDs(ids...)
	return ic
}

// AddPosts adds the "posts" edges to the Post entity.
func (ic *InfluencerCreate) AddPosts(p ...*Post) *InfluencerCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ic.AddPostIDs(ids...)
}

// Mutation returns the InfluencerMutation object of the builder.
func (ic *InfluencerCreate) Mutation() *InfluencerMutation {
	return ic.mutation
}

// Save creates the Influencer in the database.
func (ic *InfluencerCreate) Save(ctx context.Context) (*Influencer, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InfluencerCreate) SaveX(ctx context.Context) *Influencer {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InfluencerCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InfluencerCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InfluencerCreate) defaults() {
	if _, ok := ic.mutation.Status(); !ok {
		v := influencer.DefaultStatus
		ic.mutation.SetStatus(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := influencer.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := influencer.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InfluencerCreate) check() error {
	if _, ok := ic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Influencer.name"`)}
	}
	if _, ok := ic.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Influencer.platform"`)}
	}
	if _, ok := ic.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Influencer.account_id"`)}
	}
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Influencer.status"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Influencer.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Influencer.updated_at"`)}
	}
	return nil
}

func (ic *InfluencerCreate) sqlSave(ctx context.Context) (*Influencer, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Influencer.ID type: %T", _spec.ID.Value)
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InfluencerCreate) createSpec() (*Influencer, *sqlgraph.CreateSpec) {
	var (
		_node = &Influencer{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(influencer.Table, sqlgraph.NewFieldSpec(influencer.FieldID, field.TypeString))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.Name(); ok {
		_spec.SetField(influencer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ic.mutation.Platform(); ok {
		_spec.SetField(influencer.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := ic.mutation.AccountID(); ok {
		_spec.SetField(influencer.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(influencer.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(influencer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(influencer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ic.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   influencer.PostsTable,
			Columns: []string{influencer.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InfluencerCreateBulk is the builder for creating many Influencer entities in bulk.
type InfluencerCreateBulk struct {
	config
	err      error
	builders []*InfluencerCreate
}

// Save creates the Influencer entities in the database.
func (icb *InfluencerCreateBulk) Save(ctx context.Context) ([]*Influencer, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Influencer, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InfluencerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InfluencerCreateBulk) SaveX(ctx context.Context) []*Influencer {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InfluencerCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InfluencerCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
