// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/WuPinYi/SocialForge/internal/ent/influencer"
	"github.com/WuPinYi/SocialForge/internal/ent/post"
	"github.com/WuPinYi/SocialForge/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	influencerFields := schema.Influencer{}.Fields()
	_ = influencerFields
	// influencerDescStatus is the schema descriptor for status field.
	influencerDescStatus := influencerFields[4].Descriptor()
	// influencer.DefaultStatus holds the default value on creation for the status field.
	influencer.DefaultStatus = influencerDescStatus.Default.(string)
	// influencerDescCreatedAt is the schema descriptor for created_at field.
	influencerDescCreatedAt := influencerFields[5].Descriptor()
	// influencer.DefaultCreatedAt holds the default value on creation for the created_at field.
	influencer.DefaultCreatedAt = influencerDescCreatedAt.Default.(func() time.Time)
	// influencerDescUpdatedAt is the schema descriptor for updated_at field.
	influencerDescUpdatedAt := influencerFields[6].Descriptor()
	// influencer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	influencer.DefaultUpdatedAt = influencerDescUpdatedAt.Default.(func() time.Time)
	// influencer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	influencer.UpdateDefaultUpdatedAt = influencerDescUpdatedAt.UpdateDefault.(func() time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescStatus is the schema descriptor for status field.
	postDescStatus := postFields[4].Descriptor()
	// post.DefaultStatus holds the default value on creation for the status field.
	post.DefaultStatus = postDescStatus.Default.(string)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[5].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[6].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
}
