// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Influencer is the predicate function for influencer builders.
type Influencer func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
